apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service-deployment
  labels:
    app: front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      imagePullSecrets:
        - name: ibm-cloud-secret # Image pull secret added here
      containers:
        - name: front-service
          image: icr.io/ecommerceapp1/frontend-app:latest  # Your image from IBM Cloud
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 2
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 2
            failureThreshold: 1
