apiVersion: v1
kind: Service
metadata:
  name: backend-service-port
spec:
  sessionAffinity: None
  selector:
    app: backend-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
